---
- name: add to cluster
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Get cephadm public key from admin node
      delegate_to: localhost
      command: ceph cephadm get-pub-key
      register: cephadm_pubkey
      run_once: true

    - name: Ensure .ssh directory exists on remote hosts
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Add cephadm public key to authorized_keys
      authorized_key:
        user: root
        key: "{{ cephadm_pubkey.stdout }}"

    - name: add hosts to the cluster
      ceph_orch_host:
        name: "{{ ansible_facts['hostname'] }}"
        address: "{{ ansible_host }}"
        docker: true
      delegate_to: localhost

    - name: list hosts in the cluster
      when: inventory_hostname in groups['admin']
      ansible.builtin.shell:
        cmd: ceph orch host ls
      register: host_list

    - name: print current list of hosts
      when: inventory_hostname in groups['admin']
      debug:
        msg: "{{ host_list.stdout }}"
